"""create users and user_roles  tables

Revision ID: 4a7fab7a63d6
Revises: dd34ff8a04cd
Create Date: 2025-09-04 09:02:47.907380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a7fab7a63d6'
down_revision: Union[str, Sequence[str], None] = 'dd34ff8a04cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
